### ISSUE TITLE
Poor scrolling performance on iOS 9

### ISSUE THREAD

**Issue by alhill10** [lxcid/LXReorderableCollectionViewFlowLayout#97]
Hey there, has anyone else been seeing fairly sluggish scrolling behavior with this library as opposed to a built in UICollectionView? My views are not animating very smoothly on a large display like the 6S Plus.

**Comment by meiwin** [comment]
We've been seeing poor performance since iOS 9, but it is mostly caused by other reason. Some examples:
- `UIImage -imageNamed:` is very slow (fixed in iOS 9.1)
- If you've used masking and corner radius, it can contribute to degraded scrolling performance as well

The only way to find out the root cause is profiling.
